dontinline com/sakulabo/application/app/gui/MenuPanelParts/FileMenuParts/FileMenu/DataImportJFileChooser createJFileChooser()Ljavax/swing/JFileChooser;
dontinline com/sakulabo/application/app/gui/MenuPanelParts/FileMenuParts/FileMenu/EditScriptJFileChooser createJFileChooser()Ljavax/swing/JFileChooser;
dontinline com/sakulabo/application/common/mixin/AppMixin setSize(Ljava/awt/Component;)V
dontinline com/sakulabo/application/common/code/BaseCode createResourceName()Ljava/lang/String;
dontinline com/sakulabo/application/common/code/BaseCode createResourceBundle()Ljava/util/ResourceBundle;
dontinline com/sakulabo/application/common/mixin/JMenuItemMixin setJMenuItem(Lcom/sakulabo/application/app/gui/MenuPanelParts/AppMenu;)V
dontinline com/sakulabo/application/common/mixin/JTabbedPaneMixin createTabbedPane()Ljavax/swing/JTabbedPane;
dontinline com/sakulabo/application/common/code/BaseCode createException()V
dontinline com/sakulabo/application/common/mixin/JTextComponentMixin applyMacKeyBindings()V
dontinline com/sakulabo/application/common/mixin/AppMixin getWidthSize(Ljava/awt/Component;)I
dontinline com/sakulabo/application/common/mixin/AppMixin getWidthPreferredSize(Ljava/awt/Component;)I
dontinline com/sakulabo/application/common/mixin/JToolBarMixin createJToolBar()Ljavax/swing/JToolBar;
dontinline com/sakulabo/application/common/mixin/JSplitPanelMixin createSplitPane()Ljavax/swing/JSplitPane;
dontinline com/sakulabo/application/common/mixin/AppMixin getHeightSize(Ljava/awt/Component;)I
dontinline com/sakulabo/application/common/mixin/JFrameMixin createFrame()Ljavax/swing/JFrame;
dontinline com/sakulabo/application/helper/FramePositionHelper saveFramePosition(Ljavax/swing/JFrame;)V
dontinline com/sakulabo/application/common/mixin/JTextComponentMixin setUndo()V
dontinline com/sakulabo/application/common/mixin/JPanelMixin setJPanel(Ljavax/swing/JPanel;)V
dontinline com/sakulabo/application/helper/FramePositionHelper lordFramePosition(Ljavax/swing/JFrame;)V
dontinline com/sakulabo/application/app/gui/MenuPanelParts/SettingMenuParts/SettingMenu/ExportBackupDialog createJFileChooser()Ljavax/swing/JFileChooser;
dontinline com/sakulabo/application/common/mixin/JButtonMixin setJButton(Lcom/sakulabo/application/common/mixin/JButtonMixin;Ljavax/swing/JButton;)Ljava/util/Optional;
dontinline com/sakulabo/application/common/mixin/AppMixin setPreferredSize(Ljava/awt/Component;)V
dontinline com/sakulabo/application/common/mixin/JLabelMixin setJLabel(Ljavax/swing/JLabel;)V
dontinline com/sakulabo/application/common/mixin/JFileChooserMixin createJFileChooser()Ljavax/swing/JFileChooser;
dontinline com/sakulabo/application/app/gui/MenuPanelParts/SettingMenuParts/SettingMenu/ImportBackupDialog createJFileChooser()Ljavax/swing/JFileChooser;
dontinline com/sakulabo/application/common/mixin/AppMixin getHeightPreferredSize(Ljava/awt/Component;)I
dontinline com/sakulabo/application/common/mixin/JDialogMixin createJDialog(Ljava/lang/String;Lcom/sakulabo/application/common/code/GUIText;)Ljavax/swing/JDialog;
dontinline com/sakulabo/application/common/mixin/JLabelMixin createLabel()Ljavax/swing/JLabel;
