###########################################################################
# [役割]
# アプリケーションロギングの共通的なメッセージを提供します
# [使用]
# com.sakulabo.core.Logger.AppLogger
###########################################################################

###########################################################################
# COMMON
###########################################################################
COMMON_X0001=Success
COMMON_X0002=Fail
COMMON_X0003=ArchiveFile

###########################################################################
# FINEST
###########################################################################
FINEST_MSG_3001=Lorded {0} >> Status {1}
FINEST_MSG_3002={0} {1} : {2}

###########################################################################
# FINER
###########################################################################
FINER_MSG_4001=[SessionID:{0}] KSQLの実行を開始します
FINER_MSG_4002=[SessionID:{0}] KSQLの実行を終了します

###########################################################################
# WARNING
###########################################################################
WARNING_MSG9001=[Entry:{0}] 不正なバックアップエントリーです
WARNING_MSG9002=[SessionID:{0}] キャッシュは無効化されています【CacheID】: {1}
WARNING_MSG9003=[SessionID:{0}] キャッシュが無効化されました【CacheID】: {1}
WARNING_MSG9004=パラメータはシステム管理されているため上書きされました【ParamName】: {0}
WARNING_MSG9005=スクリプト環境変数はシステム管理されているため上書きされました【ScriptEnvName】: {0}
WARNING_MSG9006=日付関連スクリプト環境変数の設定に失敗しました【Pattern】: {0}
WARNING_MSG9007=システム管理下のスクリプト環境変数の設定に失敗しました【Env】: {0}