package com.sakulabo.core.Processor.database.impl;

import java.sql.Connection;
import java.sql.SQLException;

import com.sakulabo.core.Processor.archive.DataSet;
import com.sakulabo.core.Processor.database.DDLCreater;

/**
 * MySQLモード向けのDDLを生成します
 * 
 * @author keeeeeent
 */
public final class MySQLDDLCreater extends DDLCreater {

	/**
	 * デフォルトコンストラクタ
	 * @param dataSet データ構造体
	 */
	public MySQLDDLCreater(DataSet dataSet) {
		super(dataSet);
	}

	/** {@inheritDoc} */
	@Override
	public String isPK() {
		String colName = "KDB_PK_NO";
		String definition = " BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
		return colName.concat(definition);
	}

	/** {@inheritDoc} */
	@Override
	public String isNULL() {
		String colName = dataSet.columnList()[index++];
		String definition = " CHAR(1) DEFAULT NULL";
		return colName.concat(definition);
	}

	/** {@inheritDoc} */
	@Override
	public String isBOOLEAN() {
		String colName = dataSet.columnList()[index++];
		String definition = " TINYINT DEFAULT 0";
		return colName.concat(definition);
	}

	/** {@inheritDoc} */
	@Override
	public String isNUMBER() {
		String colName = dataSet.columnList()[index++];
		String definition = " BIGINT";
		return colName.concat(definition);
	}

	/** {@inheritDoc} */
	@Override
	public String isDECIMAL() {
		String colName = dataSet.columnList()[index++];
		String definition = " DECIMAL";
		return colName.concat(definition);
	}

	/** {@inheritDoc} */
	@Override
	public String isDATE() {
		String colName = dataSet.columnList()[index++];
		String definition = " DATE DEFAULT CURRENT_DATE";
		return colName.concat(definition);
	}

	/** {@inheritDoc} */
	@Override
	public String isTIMESTAMP() {
		String colName = dataSet.columnList()[index++];
		String definition = " TIMESTAMP DEFAULT CURRENT_TIMESTAMP";
		return colName.concat(definition);
	}

	/** {@inheritDoc} */
	@Override
	public String isVARCHAR() {
		int idx = index++;
		String colName = dataSet.columnList()[idx];
		long size = dataSet.dataSize()[idx];
		String definition;
		if (500 < size) {
			definition = " TEXT";
		} else {
			definition = " VARCHAR(%d)".formatted(size);
		}
		return colName.concat(definition);
	}

	/** {@inheritDoc} */
	@Override
	public void init(Connection connection) throws SQLException {
		;
	}

}
