###########################################################################
# [役割]
# アプリケーション実行環境に必要なシステム変数を設定します
# [使用]
# com.sakulabo.launcherモジュール
###########################################################################
app.io.tmpdir               =.kagerow/tmp
app.io.archivedatadir       =.kagerow/database
app.logs.dir                =.kagerow/logs
LoardDIBeans.Adapter        =com.sakulabo.core.Provides.LoardDIBeansProvider