package com.sakulabo.core.Processor.database;

import static org.hamcrest.CoreMatchers.*;
import static org.hamcrest.MatcherAssert.*;

import java.util.Collections;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.sakulabo.BaseTest;
import com.sakulabo.core.Kagerow.Contents.KagerowVirtualFileContent.KagerowDataType;
import com.sakulabo.core.Processor.archive.DataSet;
import com.sakulabo.core.Processor.database.impl.H2DDLCreater;

/**
 * H2モード向けのDDLを生成テストです
 */
public class H2DDLCreaterTest extends BaseTest<H2DDLCreater> {

	/** テスト対象 */
	private H2DDLCreater testTarget;

	/**
	 * デフォルトコンストラクタ
	 */
	protected H2DDLCreaterTest() {
		super(H2DDLCreaterTest.class);
	}

	@BeforeEach
	void initService() {
	}

	@AfterEach
	void closeService() throws Exception {
	}

	/**
	 * [試験観点] : チャンク読み取り
	 * [期待される結果] : 正常終了すること
	 */
	@Test
	public void Test001() throws Throwable {

		// 期待値
		String exp = """
				CREATE TABLE IF NOT EXISTS test."KDB_TEST" (\
				KDB_PK_NO BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\
				col1 VARCHAR(256),\
				col2 BIGINT,\
				col3 DECIMAL,\
				col4 DATE DEFAULT CURRENT_DATE,\
				col5 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\
				col6 BOOLEAN DEFAULT FALSE,\
				col7 CHAR(1) DEFAULT NULL\
				);""";

		// テストデータ用意
		String schema = "test";
		String table = "test";
		String synonym = null;
		String[] columnList = { "col1", "col2", "col3", "col4", "col5", "col6", "col7" };
		KagerowDataType[] dataType = {
				KagerowDataType.VARCHAR,
				KagerowDataType.NUMBER,
				KagerowDataType.DECIMAL,
				KagerowDataType.DATE,
				KagerowDataType.TIMESTAMP,
				KagerowDataType.BOOLEAN,
				KagerowDataType.NULL,
		};
		long[] dataSize = { 256L, 15L, 256L };
		DataSet dataSet = new DataSet(
				schema,
				table,
				synonym,
				columnList,
				dataType,
				dataSize,
				Collections.emptyList());

		// テスト対象初期化
		testTarget = new H2DDLCreater(dataSet);
		// テスト実行
		String result = testTarget.toSql();
		// 検証
		assertThat(result, is(exp));

	}
}
